# Generated by Django 5.2.18 on 2026-10-09 13:52

from hashlib import sha1
from decimal import Decimal

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


def backfill_domain_records(apps, schema_editor):
    alias = schema_editor.connection.alias
    Warehouse = apps.get_model("supply_chain", "Warehouse")
    Inventory = apps.get_model("supply_chain", "Inventory")
    PurchaseOrder = apps.get_model("supply_chain", "PurchaseOrder")
    PurchaseOrderLine = apps.get_model("supply_chain", "PurchaseOrderLine")

    for balance in Inventory.objects.using(alias).filter(warehouse__isnull=True).iterator():
        name = (balance.location or "Unassigned location").strip()
        code = f"LOC-{sha1(name.casefold().encode('utf-8')).hexdigest()[:12].upper()}"
        warehouse, _ = Warehouse.objects.using(alias).get_or_create(code=code, defaults={"name": name})
        balance.warehouse_id = warehouse.pk
        balance.save(using=alias, update_fields=["warehouse"])

    for order in PurchaseOrder.objects.using(alias).all().iterator():
        if not PurchaseOrderLine.objects.using(alias).filter(purchase_order_id=order.pk).exists():
            PurchaseOrderLine.objects.using(alias).create(
                purchase_order_id=order.pk,
                line_number=1,
                material_id=order.material_id,
                quantity=order.quantity,
                received_quantity=0,
                unit_price=order.unit_price,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(max_length=80)),
                ('entity_id', models.CharField(max_length=80)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], max_length=20)),
                ('actor', models.CharField(default='anonymous', max_length=120)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movement_type', models.CharField(choices=[('receipt', 'Receipt'), ('issue', 'Issue'), ('adjustment', 'Adjustment')], max_length=20)),
                ('quantity_delta', models.DecimalField(decimal_places=2, max_digits=14)),
                ('balance_after', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('reference', models.CharField(blank=True, max_length=80)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('actor', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('line_number', models.PositiveSmallIntegerField()),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('received_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'ordering': ['purchase_order', 'line_number'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=80)),
                ('warehouse_type', models.CharField(choices=[('distribution', 'Distribution center'), ('factory', 'Factory'), ('supplier', 'Supplier site'), ('other', 'Other')], default='distribution', max_length=20)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddConstraint(
            model_name='purchaseorder',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='purchase_order_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorder',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='purchase_order_price_nonnegative'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='supply_chain.inventory'),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order_lines', to='supply_chain.material'),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='supply_chain.purchaseorder'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory', to='supply_chain.warehouse'),
        ),
        migrations.RunPython(backfill_domain_records, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='inventory',
            constraint=models.UniqueConstraint(condition=models.Q(('warehouse__isnull', False)), fields=('material', 'warehouse'), name='unique_material_warehouse_inventory'),
        ),
        migrations.AddConstraint(
            model_name='inventory',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='inventory_quantity_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='inventory',
            constraint=models.CheckConstraint(condition=models.Q(('reorder_point__gte', 0)), name='inventory_reorder_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='inventory',
            constraint=models.CheckConstraint(condition=models.Q(('unit_cost__gte', 0)), name='inventory_cost_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='inventorymovement',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_delta', 0), _negated=True), name='inventory_movement_nonzero_delta'),
        ),
        migrations.AddConstraint(
            model_name='inventorymovement',
            constraint=models.CheckConstraint(condition=(models.Q(('movement_type', 'receipt'), ('quantity_delta__gt', 0)) | models.Q(('movement_type', 'issue'), ('quantity_delta__lt', 0)) | models.Q(('movement_type', 'adjustment'), ('quantity_delta__gt', 0)) | models.Q(('movement_type', 'adjustment'), ('quantity_delta__lt', 0))), name='inventory_movement_direction_valid'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderline',
            constraint=models.UniqueConstraint(fields=('purchase_order', 'line_number'), name='unique_purchase_order_line_number'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='purchase_order_line_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderline',
            constraint=models.CheckConstraint(condition=models.Q(('received_quantity__gte', 0)), name='purchase_order_line_received_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderline',
            constraint=models.CheckConstraint(condition=models.Q(('received_quantity__lte', models.F('quantity'))), name='purchase_order_line_received_lte_ordered'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderline',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='purchase_order_line_price_nonnegative'),
        ),
    ]
