# Generated by Django 5.2.18 on 2026-10-09 13:35

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=180)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('unit', models.CharField(default='EA', max_length=20)),
                ('criticality', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
            ],
            options={
                'ordering': ['sku'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=180)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('country', models.CharField(blank=True, max_length=80)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('risk_score', models.PositiveSmallIntegerField(default=20, validators=[django.core.validators.MaxValueValidator(100)])),
                ('lead_time_days', models.PositiveSmallIntegerField(default=14)),
                ('status', models.CharField(choices=[('active', 'Active'), ('watch', 'Watch'), ('blocked', 'Blocked')], default='active', max_length=20)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=40, unique=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=14)),
                ('expected_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('in_transit', 'In transit'), ('received', 'Received'), ('delayed', 'Delayed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='supply_chain.material')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='supply_chain.supplier')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('origin', models.CharField(max_length=120)),
                ('destination', models.CharField(max_length=120)),
                ('carrier', models.CharField(blank=True, max_length=120)),
                ('eta', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_transit', 'In transit'), ('delayed', 'Delayed'), ('delivered', 'Delivered'), ('at_risk', 'At risk')], default='planned', max_length=20)),
                ('risk_score', models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MaxValueValidator(100)])),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='supply_chain.purchaseorder')),
            ],
            options={
                'ordering': ['eta', 'reference'],
            },
        ),
        migrations.AddField(
            model_name='material',
            name='preferred_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='supply_chain.supplier'),
        ),
        migrations.CreateModel(
            name='Disruption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('disruption_type', models.CharField(default='logistics', max_length=80)),
                ('description', models.TextField(blank=True)),
                ('affected_region', models.CharField(blank=True, max_length=120)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('review', 'Under review'), ('mitigating', 'Mitigating'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('confidence', models.PositiveSmallIntegerField(default=70, validators=[django.core.validators.MaxValueValidator(100)])),
                ('affected_shipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disruptions', to='supply_chain.shipment')),
                ('affected_supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disruptions', to='supply_chain.supplier')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.CharField(max_length=120)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('reorder_point', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='supply_chain.material')),
            ],
            options={
                'ordering': ['material__sku', 'location'],
                'constraints': [models.UniqueConstraint(fields=('material', 'location'), name='unique_material_location_inventory')],
            },
        ),
    ]
