# Generated by Django 5.2.18 on 2026-10-09 15:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chain', '0002_auditevent_inventorymovement_purchaseorderline_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataImport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity_type', models.CharField(choices=[('supplier', 'Suppliers'), ('material', 'Materials'), ('warehouse', 'Warehouses'), ('inventory', 'Inventory balances'), ('purchase_order', 'Purchase orders')], max_length=30)),
                ('duplicate_policy', models.CharField(choices=[('skip', 'Skip existing'), ('update', 'Update existing'), ('error', 'Fail on duplicates')], default='skip', max_length=12)),
                ('source_name', models.CharField(max_length=120)),
                ('file_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('preview', 'Preview'), ('committed', 'Committed')], default='preview', max_length=20)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('created_rows', models.PositiveIntegerField(default=0)),
                ('updated_rows', models.PositiveIntegerField(default=0)),
                ('skipped_rows', models.PositiveIntegerField(default=0)),
                ('error_rows', models.PositiveIntegerField(default=0)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='inventory',
            name='source_key',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='inventory',
            name='source_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='inventory',
            name='source_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='source_key',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='material',
            name='source_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='material',
            name='source_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='source_key',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='source_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='source_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='source_key',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='supplier',
            name='source_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='supplier',
            name='source_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='source_key',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='source_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='source_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DataImportRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField()),
                ('natural_key', models.CharField(blank=True, max_length=250)),
                ('action', models.CharField(choices=[('create', 'Will create'), ('update', 'Will update'), ('skip', 'Will skip'), ('error', 'Error'), ('created', 'Created'), ('updated', 'Updated'), ('skipped', 'Skipped')], max_length=12)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('record_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='supply_chain.dataimport')),
            ],
            options={
                'ordering': ['row_number'],
                'constraints': [models.UniqueConstraint(fields=('batch', 'row_number'), name='unique_import_row_number')],
            },
        ),
    ]
